#ifndef STD_INCLUDE_TORASU_STD_CONTEXT_NAMES_HPP_
#define STD_INCLUDE_TORASU_STD_CONTEXT_NAMES_HPP_

// Numeric-pipeline
#define TORASU_STD_CTX_TIME "STD::CTIME"

#endif // STD_INCLUDE_TORASU_STD_CONTEXT_NAMES_HPP_
