#ifndef STD_INCLUDE_TORASU_STD_CONTEXT_NAMES_HPP_
#define STD_INCLUDE_TORASU_STD_CONTEXT_NAMES_HPP_

/** Time in seconds (with decimal spaces)
 */
#define TORASU_STD_CTX_TIME "STD::TIME"

#endif // STD_INCLUDE_TORASU_STD_CONTEXT_NAMES_HPP_
