#ifndef STD_INCLUDE_TORASU_STD_PIPELINE_NAMES_HPP_
#define STD_INCLUDE_TORASU_STD_PIPELINE_NAMES_HPP_

// Numeric-pipeline
#define TORASU_STD_PL_NUM "STD::PNUM"

// Visual-pipeline
#define TORASU_STD_PL_VIS "STD::PVIS"

// Audio-pipeline
#define TORASU_STD_PL_AUDIO "STD::PAUDIO"

// File-pipeline
#define TORASU_STD_PL_FILE "STD::PFILE"

#endif // STD_INCLUDE_TORASU_STD_PIPELINE_NAMES_HPP_
