#ifndef STD_INCLUDE_TORASU_STD_PROPERTY_NAMES_HPP_
#define STD_INCLUDE_TORASU_STD_PROPERTY_NAMES_HPP_

#include <torasu/torasu.hpp>

#define TORASU_STD_PROP_DURATION TORASU_PROPERTY_PREFIX "STD::DUR"
#define TORASU_STD_PROP_IMG_WIDTH TORASU_PROPERTY_PREFIX "STD::WIDTH"
#define TORASU_STD_PROP_IMG_HEIGHT TORASU_PROPERTY_PREFIX "STD::HEIGHT"
#define TORASU_STD_PROP_IMG_RAITO TORASU_PROPERTY_PREFIX "STD::RATIO"

#endif // STD_INCLUDE_TORASU_STD_PROPERTY_NAMES_HPP_
