#ifndef STD_INCLUDE_TORASU_STD_PROPERTY_NAMES_HPP_
#define STD_INCLUDE_TORASU_STD_PROPERTY_NAMES_HPP_

#define TORASU_STD_PROP_DURATION "STD::DUR"
#define TORASU_STD_PROP_IMG_WIDTH "STD::WIDTH"
#define TORASU_STD_PROP_IMG_HEIGHT "STD::HEIGHT"
#define TORASU_STD_PROP_IMG_RAITO "STD::RATIO"

#endif // STD_INCLUDE_TORASU_STD_PROPERTY_NAMES_HPP_
